### PR TITLE
Fuzzy search can also go to stdout

### PR DESCRIPTION
**Pull request by moretticb**
I decoupled the fuzzy search feature (doQuery) from GUI code (runQuery), so now the search can also be used in terminal, redirecting the results to stdout. Check it in practice:

https://user-images.githubusercontent.com/10677534/228660742-ce589fe5-b51a-4ff2-91f4-d4e83b1e8fcb.mov

### CODE REVIEW

**Comment by moretticb** [comment]
oops, not yet! I have to make parameter "-m" work the same way

**Comment by moretticb** [comment]
Put some thought and it is actually better to keep this way. Simpler code and the -m case is better addressed with shell, since no GUI involved. Ready to merge 😎

**Comment by chipsenkbeil** [comment]
Thanks for the contribution!

**Comment by chipsenkbeil** [comment]
@moretticb this is now available in the [1.3.0 release](https://github.com/chipsenkbeil/choose/releases/tag/1.3.0). Thanks again!

**Pull request merged**
