### PR TITLE
#47 n5 or #10: query field support for copy paste cut undo redo

### PR DESCRIPTION
**Pull request by 750**

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
@750 per your comment about some of the copy/paste properties being renamed by MacOS, is there any concern of this breaking actively when someone is using it? I don't really know what the renaming implies in terms of risk & maintenance.

**Comment by 750** [comment]
@chipsenkbeil 
(not sure i understodd your question correctly)

Whether it will break something for people already using choose: I doubt it. 
Maybe there are people who for some reason use those very common shortcuts for something else - but that means that they already have them set to some other action, so no conflicts expected.
Relevant xkcd: https://xkcd.com/1172/

Here is some context:
* While testing this PR I enabled showing menu bar - undo was shown as "Undo Typing" instead of just "Undo".
* Option names are useful if one wants to remap something globally (like "Copy" in all applications to something other than cmd+c) or for a single app. I'm not sure whether the system renaming our option affects this feature - it probably does. If this is a problem for some people - lets wait for a bug report and then fix it

**Comment by chipsenkbeil** [comment]
Makes sense to me. Thanks! Merging now. Let me know when we want to cut a new release. You had 6 items in your QoL issue, and I think with this we're down to the last two?

**Comment by 750** [comment]
here is a video of that (bug|weird behaviour)

https://github.com/user-attachments/assets/bc27f141-de97-4363-ac26-938d739723ad

**Comment by 750** [comment]
@chipsenkbeil let's make a new release now - the last two features are not as important

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil let's make a new release now - the last two features are not as important

Release 1.4.0 is out.

**Pull request merged**
